### ISSUE TITLE
New typescript 5.0.0 `export type *` syntax not supported

### ISSUE THREAD

**Issue by SebastienGllmt** [simonhaenisch/prettier-plugin-organize-imports#107]
Typescript v5 introduces a new syntax: `export type *` that allows exporting all types from a file at once

Unfortunately, `prettier-plugin-organize-imports ` doesn't seem to support this syntax and it will just delete the `export type *` line

This isn't a regression, since the standard `export type { Foo }` notation is still working - it's just the new notation that is broken

Additionally, this only happens if there is no blank space before the `export type *` notation it seems

Notably, my file looks like this
```typescript
export * from './foo';
export { default } from './foo';
export type * from './foo';
```

**Comment by simonhaenisch** [comment]
ok you'll have to report this in the typescript repo (https://github.com/microsoft/TypeScript) since it must be a bug in the typescript source (just calling a method from there from this plugin). but before you do it, can you let me know which typescript version you're using in your project? it could just be an IDE caching issue if you recently updated the typescript version, have you tried restarting it?

**Comment by povilasDadelo** [comment]
@simonhaenisch I also have noticed that if there is a newline between imports sorting doesn't work. Is this by design?

P.s. very cool plugin

**Comment by SebastienGllmt** [comment]
Yes, you're right that restarting the IDE after the new version was installed fixed this.
