### ISSUE TITLE
Feature request: configurable import sort order

### ISSUE THREAD

**Issue by linkurzweg** [simonhaenisch/prettier-plugin-organize-imports#108]
Hello, first of all, thanks for you work on this great plugin, much appreciated! :)

It would be great, if it was possible to configure in which order the imports are sorted, maybe similar to [trivago/prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports).

I'd love to have that functionality! Maybe something like that can be implemented?

**Comment by simonhaenisch** [comment]
Not possible (unless the TypeScript API implements this which they likely never will), and not the goal of this plugin. The idea is that you don't care about the order of imports (I even have them collapsed in my IDE by default these days unless I browse someone else's code). You can search through the closed issues if you want more details, this has been asked a few times already.

The only thing that TypeScript supports since 4.7 or so is import groups separated by blank lines which will then be organized (i.e. sorted) per group.

If you want to configure the order feel free to use the Trivago plugin 🙂 imo spending time configuring sth like this is a waste of time though 😬

**Comment by linkurzweg** [comment]
> Not possible (unless the TypeScript API implements this which they likely never will), and not the goal of this plugin. The idea is that you don't care about the order of imports (I even have them collapsed in my IDE by default these days unless I browse someone else's code). You can search through the closed issues if you want more details, this has been asked a few times already.
> 
> The only thing that TypeScript supports since 4.7 or so is import groups separated by blank lines which will then be organized (i.e. sorted) per group.
> 
> If you want to configure the order feel free to use the Trivago plugin 🙂 imo spending time configuring sth like this is a waste of time though 😬

Sorry to raise this again, I should've searched the existing issues first. You make some good points, I also don't care much about the order, but other people I work with do :D The Trivago plugin unfortunately doesn't support automatic removal of unused imports, a feature that I like a lot about your plugin :)

**Comment by simonhaenisch** [comment]
Hm in that case I guess your best bet is to convince the people you work with that the order actually doesn't matter 😬
