### ISSUE TITLE
Global-to-relative spacing

### ISSUE THREAD

**Issue by vitor-belim** [simonhaenisch/prettier-plugin-organize-imports#11]
Is there any way, configuration-wise, that one could leave an empty line between global imports and relative ones?

Instead of this:
```
import { Observable, Subscription } from 'rxjs'
import { skipWhile, take } from 'rxjs/operators'
import { Test } from '../../test.model'
import * as TestStore from '../../test.action'
```

It would organize like this:
```
import { Observable, Subscription } from 'rxjs'
import { skipWhile, take } from 'rxjs/operators'

import { Test } from '../../test.model'
import * as TestStore from '../../test.action'
```

Great plugin nonetheless, keep up the good work!

**Comment by simonhaenisch** [comment]
No, that's not possible because the `organizeImports` feature of the TypeScript API doesn't support this. In fact, it doesn't have any options yet. If it adds some, then I'll expose those so they can be configured for this plugin.

I'm not planning to add any manual processing past what TypeScript's `organizeImports` does.

IMHO: no one really reads the import statements anyway, so don't worry about formatting/whitespace there 😉
