### ISSUE TITLE
I would like to ask the author, this plugin collation and later support custom collation?

### ISSUE THREAD

**Issue by cMing1997** [simonhaenisch/prettier-plugin-organize-imports#119]
First of all, I would like to thank the author for developing this plugin

I just want to ask what the plugin looks like for each type of file import, and whether it supports custom rules for subsequent imports, such as which type of import comes first and which type of import comes second

**Comment by simonhaenisch** [comment]
Hey, thanks and not sure what you mean by "type of file import" but regarding customizations, no it's not possible to change anything since the order is determined by whatever the TypeScript compiler API does. Since version 4.7 you can have import groups, separated by empty new lines, otherwise there's no options afaik.
