### ISSUE TITLE
Feature request: Preserve grouping of imports

### ISSUE THREAD

**Issue by marcuswestin** [simonhaenisch/prettier-plugin-organize-imports#15]
Hi Simon,

Thank you for the plugin! I love how it works after simply installing it, without having to configure anything.

I would like to be able to preserve the grouping and order of some imports if possible. Notably, I have one library with tons of named imports, and I would like to preserve how we always choose to have those imports come last:

```ts
import { useState } from 'react'
import api from '../shared/api'
import d from '../shared/data-types'

import {
    Button,
    Col,
    Div,
    Flex,
    FlexFix,
    Input,
    makeReactiveUI,
    Margin,
    OnTap,
    Padding,
    Row,
    ScrollCol,
    Span,
    Style,
    TextArea,
    TextView,
} from '../shared/lib/js.ui/dom'
```

Would you be willing to consider adding the ability to preserve newline-separated groups of imports? My suggestion would be to treat each newline-separated group as a standalone group, and never change their order, but to change the order of import statements within any given group.

Whether you say yes to making that happen or not: thank you for the library!

Cheers,
Marcus

**Comment by simonhaenisch** [comment]
Hi Marcus,

sorry but it's out of the scope of this package. The plugin simply invokes the TypeScript language service feature (`organizeImports`) and doesn't add any other options on top of that. Adding such a feature would mean a completely different approach with the source code that would also be significantly larger. Afaik the `organizeImports` API doesn't have any options at the moment, but if the TypeScript team adds some, I'll make sure to expose them as plugin options. You could open an upstream issue in the TypeScript repo about adding options (or do a search first, I think there are some related ones already).

But IMO the purpose of auto-import-sorting is that you can completely forget about that part of the code and not even really look at it anymore. So my advice would be to stop that convention of wanting some imports in a certain spot. I used to do that, too, but now I don't care anymore and I think it's just a waste of time because who reads the import statements anyway? I always skip to the code, and if I want to look sth up, you can use go to or peek definition and it'll open the file for you).

That being said, there are also other tools out there to do import sorting/organizing that are configurable and probably can do what you want (but those are also harder to set up 😉 ).

**Comment by marcuswestin** [comment]
Thanks a ton @simonhaenisch! Makes perfect sense, and much appreciated.

Cheers

**Comment by gotgenes** [comment]
@marcuswestin I'm not sure if you've already discovered this yourself, but [trivago/prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports) looks like it might serve your needs.

**Comment by felixzy-attentec** [comment]
Looks like the desired behavior was added in TS 4.7: https://github.com/microsoft/TypeScript/issues/41494 . I still run into prettier moving my imports between groups though - not sure if this is my fault or something else.

**Comment by simonhaenisch** [comment]
Hm if you upgrade your project's TS version, it should be using that (since `typescript` is a peer dependency of this plugin, i.e. it uses the version you have installed). Have you checked running Prettier via CLI vs VS Code extension?

**Comment by felixzy-attentec** [comment]
@simonhaenisch Indeed, it seems that the vscode extension is the issue. CLI works as expected with `typescript` `4.9.3`.

**Comment by simonhaenisch** [comment]
I noticed recently that the Prettier VS Code extension always runs `prettier` with `/` (system root) as the current working directory, so my assumption is that it ends up using a different `typescript` package than the one in your project (maybe the one built into VS Code?)
