### ISSUE TITLE
Importing react at tsx files gets removed

### ISSUE THREAD

**Issue by kneczaj** [simonhaenisch/prettier-plugin-organize-imports#24]
I have a line: `import React from "react";`

It gets removed by the plugin because React is not directly used. However this import should be present in all *.tsx and *spec.tsx files so even it could be automatically added, but not really removed.

After the import gets removed, I get the following error: "React must be in scope when using JSX".

Is it possible at least to add a rule to ignore this one particular import? Do you propose any other solution or workaround?

**Comment by simonhaenisch** [comment]
Can you be a bit more specific about your setup, especially your `tsconfig`? I think something might be wrong with how you have configured `jsx` and/or `jsxFactory` (see https://www.typescriptlang.org/tsconfig). From what I recall you should have `"jsx": "react"` set. Then TypeScript should automatically notice that the import is not unused because it knows that `React.createElement` is the jsx factory.

Anyway, I doubt the problem is with this plugin, because VS Code would do the same thing if you used the "organize imports" action, if you want to try that.

**Comment by ws456999** [comment]
same problem, is there any progress?
