### ISSUE TITLE
can I disable removing unused imports in eslintrc.js?

### ISSUE THREAD

**Issue by zoffyzhang** [simonhaenisch/prettier-plugin-organize-imports#25]

**Comment by simonhaenisch** [comment]
This plugin has nothing to do with ESLint, it's for Prettier. It uses `organizeImports` from the TypeScript language service, and no, there's no option to disable removing unused imports.

There are also import-sorting rules for ESLint out there which are auto-fixable, if you want to go that route. I work with some projects that do that and it works well. Personally I disable all linter rules related to formatting and just let Prettier take care of it, because I don't want to see linter warnings about formatting all over the place while writing code.

**Comment by Abdelmuttalib** [comment]
`'unused-imports/no-unused-imports': 'warn',`

Removing this line/rule from eslintrc.js did the trick for me.

**Comment by 7kms** [comment]
I met this problem because of I have used a prettier plugin [prettier-plugin-organize-imports](https://github.com/simonhaenisch/prettier-plugin-organize-imports) which would auto remove unused imports.

Add a special config ` "organizeImportsSkipDestructiveCodeActions": true,`  in `.prettierrc` to disable this:

```json
{
  "plugins": [
    "prettier-plugin-organize-imports",
  ],
..... omit some other fileds
..... below is the critical config
  "organizeImportsSkipDestructiveCodeActions": true,
}

```

**Comment by simonhaenisch** [comment]
Yup correct, the feature has been added in [v3.1.0](https://github.com/simonhaenisch/prettier-plugin-organize-imports/releases/tag/v3.1.0).

**Comment by needfulthing** [comment]
I also had eslint removing a used import in VS Code. This seems to be a bug. Quickfix was to use `// eslint-disable-next-line`.

**Comment by simonhaenisch** [comment]
You're probably using `eslint-plugin-prettier`, i.e. running Prettier through ESLint and then using `eslint --fix` to fix formatting?

Are you linting only a part of a file by any chance?
