### ISSUE TITLE
2.3.x wants to remove synthetic default imports that are actually used

### ISSUE THREAD

**Issue by tec27** [simonhaenisch/prettier-plugin-organize-imports#28]
Version 2.2.x works fine for my project, but with 2.3.x, it's started removing a bunch of imports that are actually used.

I tried pulling a minimal repro into the tests here but it (surprisingly) passed just fine, which led me to believe it might only occur with particular TS settings. I *think* it's related to the `allowSyntheticDefaultImports` setting, mainly because A) it only seems to remove default imports erroneously and B) when turning that setting off in my project, the TS compiler seems to error on the same imports it wants to remove.

Minimal-ish repro code is:

```typescript
import Koa from 'koa'

export interface FileStore {
  write(filename: string, data: Readable, options: any): Promise<any>
  addMiddleware(app: Koa): void
}
```

2.2.x will leave the `Koa` import, 2.3.x removes it

**Comment by simonhaenisch** [comment]
Hey thanks for reporting this issue. I added your code as a test case but it doesn't fail for me with either setting of `allowSyntheticDefaultImports`. Could you please share the `compilerOptions` section of your `tsconfig.json` (you can leave any paths out)?

**Comment by simonhaenisch** [comment]
I'm not really sure how to implement a `LanguageServiceHost` class properly, so in ac62ce0 I added some file system related methods to the class. Somehow the fact that the `fileExists` method was [implemented](https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/ac62ce0da38984e4b7cbb7ae6020149042690afa/lib/service-host.js#L25) caused this problem 🤷🏻‍♂️ Not sure why that is but since the plugin was working fine without it before, I just removed this and the other new methods.

`2.3.3` is already published with the fix.
