### ISSUE TITLE
Reasoning behind this plugin

### ISSUE THREAD

**Issue by etiennejcharles** [simonhaenisch/prettier-plugin-organize-imports#3]
I'm curious of the reasons why you decided to create this plugin.
Isn't using in vscode: 

```
"editor.codeActionsOnSave": {
    "source.organizeImports": true ⬅️ 
}
```
Enough? 
Good job on the plugin by the way!

**Comment by simonhaenisch** [comment]
Thanks for the question! I (and many others) have been wanting this feature as part of Prettier for a long time. The main reason for me is that I see imports as just a list of directives which tell the program what other stuff i'm referencing and where it comes from... it's not really part of the code/program imo.

Prettier has a rationale for not doing code transformations, and sorting imports does change the AST, so Prettier has rejected the idea, which I guess is good to keep its scope lean. However, as I said I don't really think of imports as part of the actual code, so I don't see how that rationale should have to apply for import order as well. (That is, as long as you don't use side-effect imports because in that case the order can matter, but it's a bad pattern anyway.)

I think we can agree that issues with import statements are just a chore when doing code reviews or dealing with merge conflicts. That's why there's multiple approaches out there for solving this. Prettier has always put this off as a task for the linter, i. e. the linter should warn about incorrectly sorted imports and offer a way to auto-fix it. I guess it's a valid idea however in practice it comes with trade-offs, e. g. the necessary dependencies are pretty big and require additional configuration, also to make the chain of prettifying plus auto-fixing work (not sure how many times Wes Bos has tweeted about this 😂).

In some very small projects I don't even use a linter and I don't want to install a whole bunch of dependencies just to have sorted imports. And in none of the projects I work on I use linter auto-fixing because all the formatting-related linter rules are turned off (thanks to Prettier), and the rest I want to know about and solve manually because the linter teaches me to become a better programmer.

The Typescript API already provides the necessary functionality, so the code of this plugin is pretty lightweight. Furthermore the plugin allows me to solve this with zero configuration. It also has no dependencies so that installs very quickly. Using this as a Prettier plugin instead of your suggested "actions on save" has two benefits: only one action-on-save instead of two, and my team is free to use an editor other than VS Code and will still have auto-sorted imports.

BTW I got the idea of using the Typescript API from a non-working code snippet in some Github issue that I can't find anymore 😅

**Comment by grabbou** [comment]
Also, VSCode removes trailing commas which this plugin respects.
