### ISSUE TITLE
[Bug] Unused import = require() are not removed

### ISSUE THREAD

**Issue by wdfinch** [simonhaenisch/prettier-plugin-organize-imports#35]
Hi there,

It seems that if we use `import = require()` style imports and we do not use the import, then it is not removed after running prettier with this plugin enabled.

This import is common in typescript. See [here](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) for more details. 

Steps to reproduce:

1. set up a project with `prettier-plugin-organize-imports`.
2. import a node library that uses `export =` syntax ([faker](https://www.npmjs.com/package/faker) will work).
3. add `import faker = require('faker')` to the top of a file.
4. run prettier and notice that the import is not removed even though it is unused.

I can submit a small demo project as well.

**Comment by simonhaenisch** [comment]
I'm not sure why that is but it's not in the scope of this package because the TypeScript API's `organizeImports` behaves this way and the plugin is just a thin wrapper around it. So you should raise a bug ticket in [microsoft/TypeScript](https://github.com/microsoft/TypeScript) instead, however I'm not sure this is actually a bug... you may have luck finding something about this in their issues already.

BTW why don't you just use the `import * as faker from 'faker'` syntax?
