### ISSUE TITLE
It it possible to only run this as part of lint-staged? 

### ISSUE THREAD

**Issue by MelonCode** [simonhaenisch/prettier-plugin-organize-imports#38]
Hello! 
While I found import sorting very useful, sometimes, if it's used along with auto-save, it creates a problems, like for example when it removes imports for the code you just cut to paste to another place, or commented out for a second to test something. 

Is it possible to only run when you commit changes, as part of pre-commit hook, but not on every single format? 
Or may be just disable it by default, so it would be possible to use different prettier config for those scenarios? 

Thanks!

**Comment by simonhaenisch** [comment]
Just a quick update: since there's now a new `organizeImportsSkipDestructiveCodeActions` config option, you can also use that instead of `plugins`/`pluginSearchDirs`.

**Comment by raine** [comment]
I concur with the fact that this plugin can be really annoying with the way it removes imports. Doesn't suit my dev workflow at all.

`organizeImportsSkipDestructiveCodeActions` appears to work, but the problem is that this is a large project with many people and different preferences, and for now I'd like to just disable this behavior for myself without starting a discussion about how prettier should be configured for everyone.

For now I will go with adding `"organizeImportsSkipDestructiveCodeActions": true` to `.prettierrc` and ignoring the change with `git update-index --assume-unchanged`.

I think there probably should be a way to configure this behavior via an environment variable.

**Comment by simonhaenisch** [comment]
> this plugin can be really annoying with the way it removes imports. Doesn't suit my dev workflow at all.

> the problem is that this is a large project with many people and different preferences

Doesn't seem like the plugin is really the problem here, just your preferences/workflow is different to whoever in your company decided to add this plugin to the project. It's an opinionated approach (suits my workflow very well because I don't constantly save-to-format) so I would say it probably doesn't make sense to add it to a project with many contributors that can't align on a specific workflow regarding this.

Configuring via an environment variable doesn't make sense to me tbh... 1) Prettier doesn't support config via env vars from what I can tell, and 2) how to tell VS Code to run Prettier with that environment variable?

To get back to only running this as part of lint-staged, maybe it's also possible to do that by setting `organizeImportsSkipDestructiveCodeActions: false` in your normal config, and then running `prettier` with the `--organize-imports-skip-descrtuctive-code-actions` flag (not sure that's actually supported though). Maybe you can try that and if it works, suggest that to whoever manages that project you're working on.

**Comment by raine** [comment]
Thanks for the reply.

> suits my workflow very well because I don't constantly save-to-format

Yeah, that makes sense. I do have format on file save and this behavior of removing unused imports as default is just incompatible with that. I suppose it's clear that whoever decided to introduce this behavior in the project doesn't format on file save. Anyway, I'm just doing a drive by change for a few days in this project and was looking for a way to disable the behavior in a nice way that doesn't impact others. The `git update-index --assume-unchanged` works for now.

**Comment by simonhaenisch** [comment]
Cool

> I do have format on file save

Same, I just stopped hitting save until I'm done with a chunk of code that I actually want to run (: Thanks to hot exit on macOS so even if Code crashes I wouldn't loose any work.

**Comment by ajfranzoia** [comment]
For anyone interested, I implemented this plugin inside a Github action by doing:

- create a dedicated `.prettierrc.ci.js` file with the plugins config set as 
```js
module.exports = {
  "plugins": [process.env.NPM_GLOBAL_DIR + "/prettier-plugin-organize-imports/index.js"]
}
```
- add an install step `npm install -g --force prettier-plugin-organize-imports`
- run Prettier using `NPM_GLOBAL_DIR=$(npm root -g) npx prettier --config .prettierrc.ci.js`
- finally commit changes using `stefanzweifel/git-auto-commit-action@v4`
