### ISSUE TITLE
Plugin doesn't respect tslint:disable:ordered-imports rule

### ISSUE THREAD

**Issue by danjor38** [simonhaenisch/prettier-plugin-organize-imports#4]
Hello,

First, thank you for your library :)

We found an issue when we specify a file not to reorder imports by adding :

`//  tslint:disable:ordered-imports`

This is not fulfilled, imports are still reordered after adding this.

**Comment by simonhaenisch** [comment]
Yeah that's because that comment is for `tslint`, not for Prettier. This plugin has nothing to do with tslint. (maybe you were previously using tslint's auto-fixing to sort imports?)

See https://prettier.io/docs/en/ignore.html, specifically the [range ignore](https://prettier.io/docs/en/ignore.html#range-ignore) section.

```js
// prettier-ignore-start

import { foo, bar } from 'foobar';
// ...

// prettier-ignore-end

**Comment by thorn0** [comment]
Range ignore is a Markdown-only feature. Would you accept a PR that adds support for `// organize-imports-ignore`?

**Comment by simonhaenisch** [comment]
Ah ok thanks for the info, I missed that 😅 Also I just realized that any `// prettier-ignore` comments are probably not even working at the moment, because it is pre-processing done by the Typescript API (which won't care about these comments).

A related issue for Typescript is https://github.com/microsoft/TypeScript/issues/29028, with some suggestions but nothing sound yet, so at the moment there's no way to tell typescript to skip organizing imports for a certain file or certain imports.

So having your previously suggested `// organize-imports-ignore` comment would actually be a good idea! We can also respect `// tslint:disable:ordered-imports`. If you're still keen to do a PR, I'll get it merged soon, otherwise I'll see when I can find some time to do it (I personally don't need it so not high priority).

**Comment by thorn0** [comment]
The PR is here: #8
