### ISSUE TITLE
Intellij - prettier-plugin-organize-imports removes all imports

### ISSUE THREAD

**Issue by rdehuyss** [simonhaenisch/prettier-plugin-organize-imports#43]
Hi,

thanks for this great plugin - it works great when running prettier command line.

However in Intellij, it removes all imports when Intellij calls prettier (by means of the format code shortcut).  After removing this plugin again, all is well again in Intellij.

Any idea why this is?

**Comment by simonhaenisch** [comment]
Hi, I don't work with Intellij, so I'm not sure what could cause this. Just had a quick look at https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat_code and could it be that you're using the shortcut for "Reformat a code fragment in a file﻿"? There's also a mention here that it would only format a code fragment that is selected: https://www.jetbrains.com/help/idea/prettier.html#ws_prettier_reformat_code.

Maybe it would only consider the imports that are part of the code fragment you're formatting, and remove all others.

**Comment by Den-dp** [comment]
@rdehuyss what are your `Prettier` and `Actions on Save` settings?

Here are my settings that works perfectly fine:
![image](https://user-images.githubusercontent.com/1770529/143455837-a8a319eb-322f-4d02-b2f8-d4512ba6cb20.png)
![image](https://user-images.githubusercontent.com/1770529/143455863-984c6228-8da1-4f99-adb5-6b5ec2ee23b5.png)

Btw I saw @kirjs has the same problem, so let's find out the reason.

**Comment by rdehuyss** [comment]
Hi @simonhaenisch & @Den-dp, thanks for the swift feedback.

These are my Intellij settings:
![image](https://user-images.githubusercontent.com/567842/143491157-1b0c8465-93a6-4b8d-b5fe-324251abcd5f.png)


I'm not using Intellij save actions.

I'm wondering if I can enable debug logs (`DEBUG=true`) somehow...

**Comment by Den-dp** [comment]
@rdehuyss `DEBUG` is an environment variable, so can be set as usual (f.e. before launching IDE). But even if you set it - I don't know where to view `prettier-plugin-organize-imports` logs, since `Prettier` is called by Intellij Idea so all output is hidden.

But overall I'd try to set up Prettier as they "selling" it in their blog https://blog.jetbrains.com/webstorm/2020/07/webstorm-2020-2/#using_prettier_as_the_default_formatter and if it doesn't work - file an issue https://youtrack.jetbrains.com/issues

**Comment by Den-dp** [comment]
@rdehuyss looks like when `Optimize imports` setting is enabled I see a consistent repro of your problem.

![image](https://user-images.githubusercontent.com/1770529/143577164-ad9ea546-af1d-40f0-9c66-50bfb161b9f3.png)

Without this setting all works perfectly fine

**Comment by simonhaenisch** [comment]
Closing this issue now but @rdehuyss if the suggested solution doesn't fix it for you, please feel free to re-open!

**Comment by rdehuyss** [comment]
Thanks!

**Comment by kirjs** [comment]
`optimize  imports` is a great feature, and it works well for me across all other formatters, so that's definitely something that would be great to fix. 

I'm not really sure though whether the bug belongs here though, seems like this is a problem with the intellij integration, so we should prob file a bug there

**Comment by Den-dp** [comment]
I found the corresponding issue https://youtrack.jetbrains.com/issue/WEB-50178

It has only 1 vote so I recommend you to log in and vote 🙏
