### ISSUE TITLE
[Feature request] Ignore next line

### ISSUE THREAD

**Issue by luukvhoudt** [simonhaenisch/prettier-plugin-organize-imports#46]
I encountered the following use case.

Before:

```ts
import {...} from 'a-reflect-metadata-dependency';
import 'reflect-metadata';
import {...} from 'another-reflect-metadata-dependency';
```
After:

```ts
import {...} from 'another-reflect-metadata-dependency';
import {...} from 'a-reflect-metadata-dependency';
import 'reflect-metadata';
```

The `reflect-metadata` import should be imported before all files what use reflect meta data. The only way out is to ignore organize imports completely, via `// organize-imports-ignore`. However this is not ideal in my case. Ideally I would like to do something like:

Before:

```ts
// organize-imports-ignore-next-line
import 'reflect-metadata';
import {...} from 'a-reflect-metadata-dependency';
import {...} from 'another-reflect-metadata-dependency';
```

After:

```ts
// organize-imports-ignore-next-line
import 'reflect-metadata';
import {...} from 'another-reflect-metadata-dependency';
import {...} from 'a-reflect-metadata-dependency';
```

**Comment by simonhaenisch** [comment]
Sorry, that's too complicated to implement because this plugin just invokes the TypeScript language service API, and doesn't do any code modifications directly. There are discussions going on about this in the TypeScript repo already (links can be found in some older issues here iirc), and please also note that in the [readme's disclaimer](https://github.com/simonhaenisch/prettier-plugin-organize-imports#rationaledisclaimer) I mentioned that this is only good as long as your imports are side-effects free, i. e. order doesn't matter.

As a work-around I suggest you put that stuff into a separate module, e. g. `src/helpers/reflect.ts`, where you do manual sorting:

```ts
// organize-imports-ignore

import 'reflect-metadata';
import { /* ... */ } from 'a-reflect-metadata-dependency';
// ...

export { Reflect } // export a reference to the global variable
```

and then you can

```ts
import { Reflect } from '../helpers/reflect'
```

or

```ts
const { Reflect } = await import('../helpers/reflect')
```
