### ISSUE TITLE
[Feature request] Group imports from the same source

### ISSUE THREAD

**Issue by OoDeLally** [simonhaenisch/prettier-plugin-organize-imports#49]
Thanks for this awesome plugin!
Would it be possible to group imports when possible?

```ts
import { Foo } from 'foobar';
import { Bar } from 'foobar';
```
to

```ts
import { Foo, Bar } from 'foobar';
```

Thanks!

**Comment by simonhaenisch** [comment]
Not sure I follow... why don't you group them in the source already?

**Comment by OoDeLally** [comment]
There are a couple of reasons we can end up in such situation (Clumsy git merging, copy-paste, file moving/renaming, to name a few), and we would have expected prettier to group it for us.
However I agree it's not that often, so feel free to close that issue if it's not worth the work :-)

**Comment by simonhaenisch** [comment]
Oh right somehow I thought this issue was on another repo of mine 🙈

What you're asking for is already happening... I just tried it out.

<img src="https://user-images.githubusercontent.com/3410759/161020056-0c892adf-1f16-4786-b2a5-edc566ce1802.gif" width=507>

All this plugin does is invoke the TypeScript language service `organizeImports` method, which is the same as using the "organize imports" action in VS Code. If a feature is missing or not working as intended there, you'll have to reach out in the TypeScript repo.
