### ISSUE TITLE
Support compatibility with other prettier plugins

### ISSUE THREAD

**Issue by Jazcash** [simonhaenisch/prettier-plugin-organize-imports#51]
In the readme, it states:

> Caveat

> This plugin inherits, extends and overrides the built-in Prettier parsers for babel, babel-ts, typescript and vue, i. e., it's incompatible with other plugins that do the same... so only the last loaded plugin that exports one of those parsers will function.

I want to use this with `prettier-plugin-multiline-arrays`, but when this plugin is installed then it doesn't work at all, despite that plugin [saying it's compatible with this one](https://github.com/electrovir/prettier-plugin-multiline-arrays#compatibility), so maybe something changed?

That plugin recommends fiddling with the plugin order to get it to work, but no order works when this plugin is installed, possibly something to do with how it just works out the box without requiring being added to prettier plugins list?

```
    plugins: [
        "prettier-plugin-multiline-arrays", // doesn't work regardless of order
        "prettier-plugin-organize-imports"
    ],
```

**Comment by simonhaenisch** [comment]
Well, the readme states that this plugin is incompatible with others, whereas the other plugin claims to be compatible, so you should probably reopen your issue there. I haven't changed anything with this plugin in a while. Maybe something changed with Prettier's plugin API, or the other plugin.

Just looking at your plugins config though, have you tried with relative paths to the plugins, instead of just the names? Also, according to the other readme, it should be multiline-arrays last.
