### ISSUE TITLE
Pasting into import in VS Code with formatOnPaste and plugin enabled deletes entire import that is not unused

### ISSUE THREAD

**Issue by nguerrera** [simonhaenisch/prettier-plugin-organize-imports#53]
# Repro steps

1. Install VS Code and [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
2. git clone https://github.com/nguerrera/repro-import-paste
3. open newly clone repo folder in VS Code
4. open test.ts.
5. Copy the 'b' to the clipboard
6. Place cursor after 'a', type ',', Ctrl+V to paste

![repro](https://user-images.githubusercontent.com/75470/173138130-b3fd5f2a-4e86-4961-9f48-903b61b9a010.gif)

# Known workarounds

* Disable editor.formatOnPaste in .vscode/settings.json
* Ctrl-Z to undo a bad import removal

# Environment

## VS Code 
```
Version: 1.69.0-insider (user setup)
Commit: ab6ba241145bb81c8bc0f323453bbec45fd66109
Date: 2022-06-10T05:16:34.957Z (14 hrs ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22621
```

## Prettier Extension
```
v9.5.0
```

**Comment by simonhaenisch** [comment]
Thanks for the issue, i've never used format-on-paste. Can't really do anything about this, as this plugin can not detect what triggered a prettier run (this is not a VS Code plugin). There's feature request #37 to allow switching to `sortImports` instead of `organizeImports`, which is the only good solution I can think of (but it means you'll have to clean up unused imports yourself). However no one has been working on it yet and i don't have the time or need currently.
