### ISSUE TITLE
Compatibility with eslint

### ISSUE THREAD

**Issue by tobiasdiez** [simonhaenisch/prettier-plugin-organize-imports#65]
The following order is correct for the prettier-plugin
```ts
import { gql } from '~/apollo'
import Tags from './tagify.vue'
```
but eslint's `import/order` rule would like to switch it. It would be nice if the prettier-plugin and eslint's rule would be compatible by default (i.e. to use prettier while coding and eslint for ci).

**Comment by simonhaenisch** [comment]
Those can't be compatible. ESLint's `import/order` has nothing to do with how the TypeScript API organizes imports. Both are opinionated in different ways and I can't change either of them.

If you use this plugin and ESLint, then you have two options:

- Use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) with the recommended config where `"plugin:prettier/recommended"` is the **last** extension in your list of `extends` (which should automatically disable `import/order` and you shouldn't manually enable it). This way anything that's not formatted according to Prettier's style will be reported as a linter error, and you'll be able to auto-fix it (i. e. running `eslint . --fix` will have the same effect as running `prettier .` directly). When you run `eslint .` in the CI, it'll complain when anything is not formatted correctly.
- use [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier), which disables all formatting-related lint rules, and then your linting step becomes a combination of `eslint .` and `prettier --check .`. This is the officially recommended way of setting up ESLint + Prettier. Now, when you run `eslint .` in the CI it won't check any formatting, which is why you'll also have to run `prettier --check .` as part of the linting step in the CI.

For more info on this you can read up on https://prettier.io/docs/en/integrating-with-linters.html.

**Comment by tobiasdiez** [comment]
Thanks for your explanation. This was really helpful!

If this plugin is not compatible with eslint's import/order rule, then maybe its a good idea to add this to the documentation and/or disable the eslint rule as part of eslint-config-prettier (not sure if they can detect that this prettier plugin is installed). What do you think?

**Comment by simonhaenisch** [comment]
I don't think the Prettier team will want to add this to `eslint-config-prettier` (see discussion on [this PR](https://github.com/prettier/prettier/pull/9417)), even though it would be cool if it could be dependent on detecting the plugin.

Could add a note to the readme, even though I think it's relatively obvious that this would clash with other mechanisms to auto-sort imports. But yeah, might help some people, plus could add a note about how to use in combination with ESLint.
