### ISSUE TITLE
Would it be possible to make prettier obey eslint's rules through this plugin?

### ISSUE THREAD

**Issue by Evertt** [simonhaenisch/prettier-plugin-organize-imports#76]
I have a very specific way that I'd like to order my imports and I defined it in my eslint rules:

```js
{
  rules: {
    "import/order": [
      "error",
      {
        groups: [
          "type",
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
        ],
        pathGroups: [
          {
            pattern: "@/**",
            group: "internal",
          },
        ],
        alphabetize: {
          order: "asc",
        },
      },
    ],
  }
}
```

I'd really love to find a way to make prettier let eslint order my imports and then completely ignore the final result, whether it conforms to prettier's preferred order or not.

Can you maybe advise me how to do that? I'd be happy to write my own plugin for that if necessary.

### Edit

Oh yeah and the feature to automatically delete unused imports is actually also very nice. So if I'm gonna build my own plugin anyway, then I'd love to include that feature too.

**Comment by simonhaenisch** [comment]
Please have a look at #65 which is a somewhat similar question.

Otherwise, there's a few things to clarify:

1. Prettier has no preferred order, I assume you're talking about the order that this plugin produces through the TypeScript language service API's `organizeImports` method?
2. Not sure what you mean by Prettier letting ESLint order your imports? Prettier doesn't order imports by default (i.e. without this plugin), so if you want ESLint to order your imports, just don't use this plugin and run ESLint with `--fix` flag. Afaik the `import/order` core rule is not very auto-fixable though (or maybe it wasn't but is now?).
3. Not sure what you mean by "completely ignoring the final result"?

Anyway, my best guess for what you want is to run Prettier first and ESLint's auto-fix second. This way Prettier will first use this plugin to format the imports according to the TS language service API's feature (which includes removing unused imports), then you'll get ESLint to sort them the way you set ESLint up (assuming that the `import/order` rule is somewhat auto-fixable by now).

There's a few different options to get there... e. g. by adding a run-script that invokes both CLIs consecutively:

```js
// package.json

{
  "scripts": {
    "format": "prettier --write . && eslint --fix ."
  }
}
```

In your editor you can also do that, e.g. in VS Code you can enable the Prettier extension and then also add `"editor.codeActionsOnSave": { "source.fixAll": true }` to your settings (you need to have the ESLint extension installed for that as well). Not entirely sure it'll always run in the desired order though 🤷🏻‍♂️

Or you use [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) and similarly first extend `prettier`, then configure `import/order` after that. This way you'll still have to run Prettier and ESLint though.

Maybe the best way for your goal is to use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and configure `import/order` after `prettier/prettier`, then just run `eslint --fix .` (or `source.fixAll` in your editor) and disable the Prettier extension in your editor.
