### ISSUE TITLE
Ignores bracketSpacing option

### ISSUE THREAD

**Issue by TrevinAvery** [simonhaenisch/prettier-plugin-organize-imports#85]
When `bracketSpacing` is set to `false` in the `package.json` file, this option is ignored while organizing imports and spaces are still added. I don't know if this is ignored from `.prettierrc`.

### package.json file:
```json
{
  "prettier": {
    "bracketSpacing": false
  }
}
```

**Comment by simonhaenisch** [comment]
Hey not sure what exactly you mean, can't reproduce.

Sometimes, after changing the Prettier config, you need to reload the VS Code window, becuase the Prettier extension does some caching. Or, if you're talking about the "Organize Imports" VS Code action adding spaces, then yeah that won't change and if you use this plugin, you should only format on save, not also organize imports on save.

If this issue still isn't solved for you, feel free to re-open this issue.

**Comment by TrevinAvery** [comment]
I was talking about the "Organize Imports" VS Code action. I thought this would simply run this plugin. Why is that different?

I didn't see an option for organizing imports on save. However, it does work correctly when I format on save.

**Comment by simonhaenisch** [comment]
> I was talking about the "Organize Imports" VS Code action. I thought this would simply run this plugin. Why is that different?

You might have misunderstood the readme... this Prettier plugin runs the same code of the TypeScript API that the "Organize Imports" VS Code action runs, but it doesn't run the VS Code action (and neither would the VS Code action be able to run this plugin). The Prettier plugin runs the organizing in a preprocess hook, i.e. before the code is run through the Prettier parser. That's why you get the correct bracket spacing when you format on save, because that runs Prettier (with the plugin), whereas running the VS Code action only organizes the imports but has nothing to do with Prettier.

> I didn't see an option for organizing imports on save.

VS Code has an option `editor.codeActionsOnSave` and in there you can enable `source.organizeImports` which automatically runs the VS Code action on save. I thought you might have that enabled.
