### ISSUE TITLE
Can `react-jsx` be added as a valid option in the tsconfig?

### ISSUE THREAD

**Issue by ragraff** [simonhaenisch/prettier-plugin-organize-imports#88]
Documentation calls out using `"jsx": "react"` but `"jsx": "react-jsx"` is also a valid option.

**Comment by simonhaenisch** [comment]
The case that the readme mentions is if you use the `React` import for the jsx factory "side effect" only, e.g.

```ts
import React from 'react'

export default () => <div>Hi</div>
```

In this case `React` would be unused in the source code, but not in the compiled code because `React.createElement` is the jsx factory. Thus the import statement needs to stay even though it appears unused (and if you set `jsx: 'react'` then that'll be respected by the TS API's `organizeImports` method).

If you use `react-jsx`, TypeScript will generate a different output (see [official docs](https://www.typescriptlang.org/docs/handbook/jsx.html#basic-usage)) that doesn't require the `React` import at all, i.e. you could reduce the example to

```ts
export default () => <div>Hi</div>
```

So yeah `react-jsx` is also a valid option, but imo the current docs don't imply that `react` is the only valid option... that's why the sentence starts with

> depending on your configuration, if you need the React import to stay even if it's "unused"
