### ISSUE TITLE
Add Astro support

### ISSUE THREAD

**Issue by kollinmurphy** [simonhaenisch/prettier-plugin-organize-imports#89]
Right now, it removes all imports and messes with the JSX, removing or adding random characters.

**Comment by simonhaenisch** [comment]
I haven't used Astro yet, but since it's similar to Vue or Svelte, I think Volar could provide the base tooling for it (not working for Svelte yet though, I haven't progressed on PR #80 which should solve this for Svelte).

I won't have time in the near future to work on this, so I'll wait for a contribution.

**Comment by longfellowone** [comment]
For anyone else looking I found this

https://www.npmjs.com/package/prettier-plugin-astro-organize-imports
