### ISSUE TITLE
Grouping of imports according to their type

### ISSUE THREAD

**Issue by Majidahmadi** [simonhaenisch/prettier-plugin-organize-imports#97]
This is my imports:

```
import { ConfigService } from '@nestjs/config'
import { readFile } from 'fs'
import { join } from 'path'
import { Provider } from '../interfaces/provider.abstract'
import { Helper } from '../common/helper'
```

I need imports to be categorized, based on external and internal packages:

```
import { ConfigService } from '@nestjs/config'
import { readFile } from 'fs'
import { join } from 'path'

import { Provider } from '../interfaces/provider.abstract'
import { Helper } from '../common/helper'
```

This feature is available in `Typescript Import Sorter` and other prettier plugins, is it also in this plugin?

**Comment by simonhaenisch** [comment]
This plugin has no preferences or features other than skipping files via comment and the one "skip destructive code actions" option that's mentioned in the readme. It just invokes a built-in method of the TypeScript API (same one used when using the "Organize Imports" action in VS Code), and that method so far only had the one option mentioned. Some extra ones were added in TypeScript 5 that I haven't exposes as options to the plugin yet, but I don't think any of them would be useful to achieve your desired behavior ([list of new experimental options here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#case-insensitive-import-sorting-in-editors)). That being said, there's a feature since TS 4.7 or so that import groups (separated by an empty line) will be preserved, i.e. only ordered within each group. With that you could achieve it but it would require you to put the imports into the right group manually.

> I need imports to be categorized

I would challenge that you **need** this? 😅  I've argued this in other issues before: once I stopped caring about any kind of sort logic regarding the imports and just relied on auto-imports and whatever auto-sort (alphabetically in this case), I eventually ended up barely touching the import section or even looking at it (thus I don't care about any options).

**Comment by bluebreadhead** [comment]
more power to this

**Comment by simonhaenisch** [comment]
You're free to use any other plugin if you need this but my plugin here just does what the TypeScript compiler API does, nothing else.
